general:
    printStackTraces: false
    showquery: false
database:
    username: username
    password: password
    host: localhost
    port: 3306
    database: schema
    prefix: BrohoofEcon_
economy:
    currencyName: Bit
    currencyPlural: Bits
    currencySmall: Bitlet
    currencySmallPlura: Bitlets
    currencySymbol: $
    startAmount: 100.00