name: BrohoofEconomy
author: SweetieBelle
main: com.brohoof.brohoofeconomy.BrohoofEconomyPlugin
version: $version
depend: [SweetieLib]
description: >
            Gives economy to servers.
api-version: 1.15
commands:
    money:
      description: Checks balance of you or another player
      usage: /money <other>
      permission: brohoofecon.money
      aliases: [balance]
    moneytop:
      description: View the top 10 players
      usage: /moneytop
      permission: brohoofecon.moneytop
    pay:
      description: Give money to another player from yourself
      usage: /pay target amount
      permission: brohoofecon.pay
    givemoney:
      description: Give money to another player
      usage: /givemoney target amount
      permission: brohoofecon.give
permissions:
    brohoofecon.money:
      description: Allows usage of /money
      default: true
    brohoofecon.money.other:
      description: Allows usage of /money other
      default: op
    brohoofecon.give:
      description: Allows usage of /givemoney
      default: op
    brohoofecon.moneytop:
      description: Allows usage of /moneytop
      default: true
    brohoofecon.pay:
      description: Allows usage of /pay
      default: true